package com.homan.huang.bletoled.device

enum class DeviceStatus {
    PAIRING, BONDING, DISCOVERING, SWITCHING,
    DISCOVERED, BONDED, CONNECTED,
    FAIL, DISCONNECTED, NOT_FOUND, COUNT_DOWN,
    LED_ON, LED_OFF, LED_FAIL_ON, LED_FAIL_OFF,
    RESTART
}